# ==============================================================
# Profil Docker — Base PostgreSQL locale
# ==============================================================

server.port=8081
spring.application.name=apirental

# R2DBC (réactif)
spring.r2dbc.url=r2dbc:postgresql://postgres:5432/easyrental
spring.r2dbc.username=easyrental
spring.r2dbc.password=easyrental123
spring.r2dbc.properties.ssl=false

# Liquibase (JDBC pour migrations)
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.url=jdbc:postgresql://postgres:5432/easyrental
spring.liquibase.user=easyrental
spring.liquibase.password=easyrental123
spring.liquibase.driver-class-name=org.postgresql.Driver

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# WebFlux
spring.webflux.base-path=/

# JWT
jwt.secret=${JWT_SECRET:7KyhCtwGUvIoqcxTCabQGm3FJ/F6LfCy9nmOg3hy+WA=}
jwt.expiration=86400000

# Media
application.file.upload-dir=uploads
application.base-url=http://localhost:8081
