# ==============================================================
# Server port
# ==============================================================
server.port=8081

spring.application.name=apirental

# ==============================================================
# Configuration R2DBC (Réactif - Pour l'application)
# ==============================================================

# -----------------------------------------------------
# Config pour PostgreSQL Local
# -----------------------------------------------------
spring.r2dbc.url=r2dbc:postgresql://localhost:5433/easyrental
spring.r2dbc.username=easyrental
spring.r2dbc.password=easyrental123
spring.r2dbc.properties.ssl=false
spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=1
spring.r2dbc.pool.max-size=5
spring.r2dbc.pool.max-idle-time=30s
spring.r2dbc.pool.validation-query=SELECT 1


# ==============================================================
# Configuration Liquibase (JDBC - Pour la migration au démarrage)
# ==============================================================
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# ------------------------------------------------------
# config pour PostgreSQL Local
# ------------------------------------------------------
spring.liquibase.url=jdbc:postgresql://localhost:5433/easyrental
spring.liquibase.user=easyrental
spring.liquibase.password=easyrental123
spring.liquibase.driver-class-name=org.postgresql.Driver


# ==============================================================
# Configuration Swagger (SpringDoc)
# ==============================================================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# ==============================================================
# Configuration WebFlux
# ==============================================================
spring.webflux.base-path=/

# ==============================================================
# Configuration JWT
# ==============================================================
# Clé secrète (générez-en une forte pour la prod via la variable JWT_SECRET)
jwt.secret=${JWT_SECRET:7KyhCtwGUvIoqcxTCabQGm3FJ/F6LfCy9nmOg3hy+WA=}
jwt.expiration=86400000

# ==============================================================
# Configuration MEDIA
# ==============================================================
# Dossier où les fichiers seront stockés
application.file.upload-dir=uploads
# URL de base pour construire le lien public
# application.base-url=http://localhost:8081
application.base-url=https://apirental5gi-v2.onrender.com
